In [1]:
import numpy as np

##numpy array

##numpy array

In [2]:
benimListem = [20,30,40]

In [3]:
type(benimListem)

list

In [4]:
np.array(benimListem)

array([20, 30, 40])

In [5]:
matrixListesi = [[1,20,30],[20,30,40],[30,40,50]]

In [6]:
matrixListesi[1][0]

20

In [7]:
np.array(matrixListesi)

array([[ 1, 20, 30],
       [20, 30, 40],
       [30, 40, 50]])

##arange

In [8]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [9]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

##zeros

In [11]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [12]:
np.zeros((9,9))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [13]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [14]:
np.ones((9,9))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.]])

##linspace

In [15]:
np.linspace(0,20,5)

array([ 0.,  5., 10., 15., 20.])

In [16]:
np.linspace(0,20,6)

array([ 0.,  4.,  8., 12., 16., 20.])

In [17]:
np.linspace(1,10,100)

array([ 1.        ,  1.09090909,  1.18181818,  1.27272727,  1.36363636,
        1.45454545,  1.54545455,  1.63636364,  1.72727273,  1.81818182,
        1.90909091,  2.        ,  2.09090909,  2.18181818,  2.27272727,
        2.36363636,  2.45454545,  2.54545455,  2.63636364,  2.72727273,
        2.81818182,  2.90909091,  3.        ,  3.09090909,  3.18181818,
        3.27272727,  3.36363636,  3.45454545,  3.54545455,  3.63636364,
        3.72727273,  3.81818182,  3.90909091,  4.        ,  4.09090909,
        4.18181818,  4.27272727,  4.36363636,  4.45454545,  4.54545455,
        4.63636364,  4.72727273,  4.81818182,  4.90909091,  5.        ,
        5.09090909,  5.18181818,  5.27272727,  5.36363636,  5.45454545,
        5.54545455,  5.63636364,  5.72727273,  5.81818182,  5.90909091,
        6.        ,  6.09090909,  6.18181818,  6.27272727,  6.36363636,
        6.45454545,  6.54545455,  6.63636364,  6.72727273,  6.81818182,
        6.90909091,  7.        ,  7.09090909,  7.18181818,  7.27

##eye

In [18]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

## random

In [20]:
np.random.randn(4)

array([-0.62700812, -0.37136384, -0.49279047, -0.34010881])

In [21]:
np.random.randn(4,4)

array([[ 0.3378087 ,  0.30058125,  0.4561432 ,  0.2281405 ],
       [ 0.96370677,  2.24083412,  1.06682076,  0.38841295],
       [-0.29906928, -0.95053265, -0.24703669, -1.68936592],
       [-1.697227  , -0.51036842,  0.98353662,  0.57070123]])

In [24]:
np.random.randint(1,10)

5

In [25]:
np.random.randint(1,300,5)

array([232, 200,  32, 121, 142])

In [26]:
benimNumpyDizim = np.arange(30)

In [27]:
benimNumpyDizim

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [28]:
benimRandomDizim = np.random.randint(0,100,30)

In [29]:
benimRandomDizim

array([ 7, 60, 43,  4, 95, 43, 96, 77, 28, 21, 10, 50, 88, 19, 48, 55, 60,
       49,  7, 68, 84, 29, 62, 22, 61, 23, 55, 64, 53,  6])

## numpy dizi methodları

In [30]:
benimNumpyDizim.reshape(5,5)

ValueError: cannot reshape array of size 30 into shape (5,5)

In [31]:
benimNumpyDizim.reshape(6,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [32]:
benimNumpyDizim.max()

29

In [33]:
benimRandomDizim.min()

4

In [34]:
benimRandomDizim.argmin()

3

In [36]:
reshapeDizim = benimNumpyDizim.reshape(5,6)

In [37]:
reshapeDizim.shape

(5, 6)

In [38]:
reshapeDizim

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [40]:
benimDizim = np.arange(0,15)

In [41]:
benimDizim

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [43]:
benimDizim[3:8]

array([3, 4, 5, 6, 7])

In [44]:
benimDizim[3:8] = -5

In [45]:
benimDizim

array([ 0,  1,  2, -5, -5, -5, -5, -5,  8,  9, 10, 11, 12, 13, 14])

In [46]:
baskaDizi = np.arange(0,24)

In [47]:
baskaDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [48]:
slicingDizisi = baskaDizi[4:9]

In [49]:
slicingDizisi

array([4, 5, 6, 7, 8])

In [50]:
baskaDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [51]:
slicingDizisi[:] = 700

In [52]:
slicingDizisi

array([700, 700, 700, 700, 700])

In [53]:
baskaDizi

array([  0,   1,   2,   3, 700, 700, 700, 700, 700,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23])

In [54]:
ornekDizi = np.arange(0,24)

In [55]:
ornekDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [56]:
ornekDiziKopyasi = ornekDizi.copy()

In [57]:
ornekDiziKopyasi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [58]:
ornekDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [59]:
ornekDiziKopyaSlicing = ornekDiziKopyasi[3:6]

In [60]:
ornekDiziKopyaSlicing[:] = 800

In [61]:
ornekDiziKopyaSlicing

array([800, 800, 800])

In [62]:
ornekDiziKopyasi

array([  0,   1,   2, 800, 800, 800,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23])

In [63]:
ornekDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

## Matrix

In [64]:
myList = [[10,20,30],[20,30,40],[30,40,50]]

In [65]:
myMatrixArray = np.array(myList)

In [66]:
myMatrixArray

array([[10, 20, 30],
       [20, 30, 40],
       [30, 40, 50]])

In [67]:
myMatrixArray[1,2]

40

In [68]:
myMatrixArray[0:,2]

array([30, 40, 50])

In [70]:
myMatrixArray[2:,2:]

array([[50]])

## operasyonlar

In [71]:
yeniBirDizi = np.random.randint(1,100,20)

In [72]:
yeniBirDizi

array([68, 26, 83, 61, 35,  9,  4,  7,  7, 80, 76, 18,  8, 16, 37, 24, 99,
       38, 84, 62])

In [73]:
yeniBirDizi > 24

array([ True,  True,  True,  True,  True, False, False, False, False,
        True,  True, False, False, False,  True, False,  True,  True,
        True,  True])

In [74]:
yeniBirDizi

array([68, 26, 83, 61, 35,  9,  4,  7,  7, 80, 76, 18,  8, 16, 37, 24, 99,
       38, 84, 62])

In [75]:
sonucDizisi = yeniBirDizi > 24

In [77]:
sonucDizisi

array([ True,  True,  True,  True,  True, False, False, False, False,
        True,  True, False, False, False,  True, False,  True,  True,
        True,  True])

In [78]:
yeniBirDizi

array([68, 26, 83, 61, 35,  9,  4,  7,  7, 80, 76, 18,  8, 16, 37, 24, 99,
       38, 84, 62])

In [79]:
yeniBirDizi[sonucDizisi]

array([68, 26, 83, 61, 35, 80, 76, 37, 99, 38, 84, 62])